# PREPROCESSING

In [ ]:
import re # untuk regex
import numpy as np
import pandas as pd
from nltk.stem import WordNetLemmatizer
from collections import defaultdict

global dfToken, dfFilter, dfStemmed

In [ ]:
    def tokenisasi(a:str):
        #deklarasi list untuk hasil
        token = a.split(' ')
        char = []
        final = []
        
        #HAPUS TANDA BACA menggunakan import regex
        for i in range(len(token)):
            token[i] = token[i].lower()
            text = re.sub(r'[+)(",.:@#?!&$*\s\-]', '', token[i])
            if (text != '' or text!=' '):
                char.append(text)
        #HAPUS ANGKA menggunakan import regex
        for i in range (len(char)):
            text = re.sub(r'[0-9]', '', char[i])
            if (text != '' or text != ' '):
                final.append(text)
        #mengembalikan nilai yang sudah ditokenisasi
        return (final)

In [ ]:
    def filtering(tokens:list):
        #filtering menggunakan stopword
        file = open('stopwords.txt', 'r')
        stoplist, filters = [],[]
        stoplist = file.read()
        for i in range(len(tokens)):
            if tokens[i] not in stoplist:
                    filters.append(tokens[i])
        return filters

In [ ]:
    def Preprocessing(lines:list):
        # TOKENISASI
        hasilToken = []
        
        for i in range(len(lines)):
            t = tokenisasi(lines[i])
            hasilToken.append(t)
        dfToken = pd.DataFrame(hasilToken)
        
        #FILTERING
        hasilFilter = []
        for i in range(len(hasilToken)):
            f = filtering(hasilToken[i])
            hasilFilter.append(f)
        dfFilter = pd.DataFrame(hasilFilter)
        
        #STEMMING INGGRIS dgn NLTK Lemmatizer
        Lemmatize = WordNetLemmatizer()
        hasilStemming = []
        for i in range(len(hasilFilter)):
            s = list()
            for j in range(len(hasilFilter[i])):
                ss = Lemmatize.lemmatize(hasilFilter[i][j])
                s.append(ss)
            hasilStemming.append(s)
        dfStemmed = pd.DataFrame(hasilStemming)
        return hasilStemming

In [ ]:
    def Pembobotan(stemmed: list):
        merge = []
        for i in range (len(stemmed)):
            for j in range (len(stemmed[i])):
                merge.append(stemmed[i][j])
        
        daftar = list(dict.fromkeys(merge))
        rawTF = defaultdict(dict)
        
        for key in daftar:
            for val in range(len(stemmed)):
                count = 0
                for i in range(len(stemmed[val])):
                    if(key == stemmed[val][i]):
                        count += 1
                rawTF[key][val] = count
        dfRawTF = pd.DataFrame(rawTF)
        return dfRawTF

In [ ]:
def main():
        # membuka data yang berasal dari file txt yang tiap dokumennya dipisahkan dengan baris baru
        f = open("amazon_cells_labelled_baru.txt")
        lines = f.readlines()
        #PARSING
        lines = [line.rstrip('\t') for line in open('amazon_cells_labelled_baru.txt')]
        return lines
    
#menjalankan modul           
x = main()
PP = Preprocessing(x)
print ('----------Hasil Preprocessing:')

PP

----------Hasil Preprocessing:


[['recently', 'stay', 'connected', 'minute', 'disconnected'],
 ['phone', 'tell'],
 ['sony', 'ericsson', 'thats'],
 ['battery', 'completely', 'useless'],
 ['waste', 'time'],
 ["don't", 'waste'],
 ['mistake'],
 ['disappointment', 'calendar', 'sync'],
 ['phone', 'unusable'],
 ['worst', 'customer', 'service'],
 ['additional', 'gel', 'provided', 'instruction', 'whatsoever'],
 ['defeat', 'purpose', 'bluetooth', 'headset'],
 ['internet', 'excrutiatingly', 'slow'],
 ['product',
  'strong',
  'rubber/petroleum',
  'smell',
  'unbearable',
  'caused',
  'return'],
 ['poor', 'quality', 'service'],
 ['cable', 'look', 'flimsy', 'scary'],
 ['absolutel', 'junk'],
 ["didn't"],
 ['returned', 'hour'],
 ["don't", 'waste', 'money'],
 ['drain', 'player', 'potentially', 'fry'],
 ['perfectly'],
 ['unreliable', "i'm", 'giving'],
 ['star', 'sound', 'quality'],
 ['avoid'],
 ['reversible', 'plug'],
 ['wasted', 'little', 'money', 'earpiece'],
 ['phone'],
 ['rotating', 'feature', 'helpful'],
 ['comfort', 'family']

In [ ]:
weigh = Pembobotan(PP)
global rawTF
rawTF = pd.DataFrame(weigh).transpose()

In [ ]:
rawTF

0    1    2    3    4    5    6    7    8    9    ...  740  \
recently          1    0    0    0    0    0    0    0    0    0  ...    0   
stay              1    0    0    0    0    0    0    0    0    0  ...    0   
connected         1    0    0    0    0    0    0    0    0    0  ...    0   
minute            1    0    0    0    0    0    0    0    0    0  ...    0   
disconnected      1    0    0    0    0    0    0    0    0    0  ...    0   
phone             0    1    0    0    0    0    0    0    1    0  ...    0   
tell              0    1    0    0    0    0    0    0    0    0  ...    0   
sony              0    0    1    0    0    0    0    0    0    0  ...    0   
ericsson          0    0    1    0    0    0    0    0    0    0  ...    0   
thats             0    0    1    0    0    0    0    0    0    0  ...    0   
battery           0    0    0    1    0    0    0    0    0    0  ...    0   
completely        0    0    0    1    0    0    0    0    0    0  ...    0   
useless           0    0    0    1    0    0    0    0    0    0  ...    0   
waste             0    0    0    0    1    1    0    0    0    0  ...    0   
time              0    0    0    0    1    0    0    0    0    0  ...    0   
don't             0    0    0    0    0    1    0    0    0    0  ...    0   
mistake           0    0    0    0    0    0    1    0    0    0  ...    0   
disappointment    0    0    0    0    0    0    0    1    0    0  ...    0   
calendar          0    0    0    0    0    0    0    1    0    0  ...    0   
sync              0    0    0    0    0    0    0    1    0    0  ...    0   
unusable          0    0    0    0    0    0    0    0    1    0  ...    0   
worst             0    0    0    0    0    0    0    0    0    1  ...    0   
customer          0    0    0    0    0    0    0    0    0    1  ...    0   
service           0    0    0    0    0    0    0    0    0    1  ...    0   
additional        0    0    0    0    0    0    0    0    0    0  ...    0   
gel               0    0    0    0    0    0    0    0    0    0  ...    0   
provided          0    0    0    0    0    0    0    0    0    0  ...    0   
instruction       0    0    0    0    0    0    0    0    0    0  ...    0   
whatsoever        0    0    0    0    0    0    0    0    0    0  ...    0   
defeat            0    0    0    0    0    0    0    0    0    0  ...    0   
...             ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
restocking        0    0    0    0    0    0    0    0    0    0  ...    0   
fee               0    0    0    0    0    0    0    0    0    0  ...    0   
darn              0    0    0    0    0    0    0    0    0    0  ...    0   
lousy             0    0    0    0    0    0    0    0    0    0  ...    0   
seen              0    0    0    0    0    0    0    0    0    0  ...    0   
sweetest          0    0    0    0    0    0    0    0    0    0  ...    0   
securely          0    0    0    0    0    0    0    0    0    0  ...    0   
hook              0    0    0    0    0    0    0    0    0    0  ...    0   
directed          0    0    0    0    0    0    0    0    0    0  ...    0   
canal             0    0    0    0    0    0    0    0    0    0  ...    0   
problemvery       0    0    0    0    0    0    0    0    0    0  ...    0   
unsatisfactory    0    0    0    0    0    0    0    0    0    0  ...    0   
negatively        0    0    0    0    0    0    0    0    0    0  ...    0   
provide           0    0    0    0    0    0    0    0    0    0  ...    0   
hype              0    0    0    0    0    0    0    0    0    0  ...    0   
assumed           0    0    0    0    0    0    0    0    0    0  ...    0   
lense             0    0    0    0    0    0    0    0    0    0  ...    0   
covered           0    0    0    0    0    0    0    0    0    0  ...    0   
text              0    0    0    0    0    0    0    0    0    0  ...    0   
messaging         0    0    0    0    

# NAIVE BAYES MULTINOMIAL

## FASE TRAINING

![Screen%20Shot%202019-11-26%20at%2011.30.21%20AM.png](attachment:Screen%20Shot%202019-11-26%20at%2011.30.21%20AM.png)

In [ ]:
def OpenDok(dokumen: list):                                      
    dok = pd.DataFrame(dokumen,columns=['documents'])
    return dok

In [ ]:
def Prior(c:str):
    Prior = len(Kelas(c)) / len(DFdokumen)
    return Prior

In [ ]:
def Kelas (c:str):
    kelas = DFdokumen[DFdokumen['documents'].str.contains(c)]
    return kelas

In [ ]:
def countWC (c:str):
    kelas = Kelas(c)
    fitur = rawTF[rawTF.columns[kelas.transpose().columns]].sum(axis=1)
    return fitur

In [ ]:
def Likelihood (c):
    kataW = countWC(c)
    kataC = kataW.sum()
    pembilang = kataW + 1
    penyebut = kataC + len(rawTF)
    Likelihood = pembilang / penyebut
    
    print()
    
    return Likelihood

In [ ]:
f = open("amazon_cells_labelled_baru.txt")
dokumen = f.readlines()

global DFdokumen
DFdokumen = OpenDok(dokumen)

In [ ]:
PriorPositif = Prior('1')
PriorPositif

0.49466666666666664

In [ ]:
PriorNegatif = Prior('0')
PriorNegatif

0.5386666666666666

In [ ]:
LPositif = pd.DataFrame(Likelihood('1'), columns=['Positif'])
LNegatif = pd.DataFrame(Likelihood('0'), columns=['Negatif'])

LLHood = pd.concat([LPositif,LNegatif],axis=1)
LLHood

Positif   Negatif
recently        0.000767  0.000698
stay            0.001151  0.002442
connected       0.000767  0.000698
minute          0.001919  0.001395
disconnected    0.000767  0.000698
phone           0.024175  0.023718
tell            0.000384  0.001046
sony            0.001535  0.001395
ericsson        0.000767  0.000698
thats           0.000767  0.000698
battery         0.008442  0.006627
completely      0.000767  0.002093
useless         0.000384  0.002442
waste           0.000384  0.003488
time            0.004605  0.005232
don't           0.001919  0.007325
mistake         0.000384  0.001744
disappointment  0.000384  0.002093
calendar        0.000384  0.000698
sync            0.000384  0.000698
unusable        0.000384  0.000698
worst           0.001151  0.004883
customer        0.000767  0.003139
service         0.002302  0.005232
additional      0.000767  0.000698
gel             0.000767  0.000698
provided        0.000767  0.000698
instruction     0.000384  0.001744
whatsoever      0.000384  0.001046
defeat          0.000384  0.000698
...                  ...       ...
restocking      0.000384  0.000698
fee             0.000384  0.000698
darn            0.000384  0.000698
lousy           0.000384  0.000698
seen            0.000767  0.000349
sweetest        0.000767  0.000349
securely        0.000767  0.000349
hook            0.000767  0.000349
directed        0.000767  0.000349
canal           0.000767  0.000349
problemvery     0.000384  0.000698
unsatisfactory  0.000384  0.000698
negatively      0.000384  0.000698
provide         0.000384  0.000698
hype            0.000384  0.000698
assumed         0.000384  0.000698
lense           0.000384  0.000698
covered         0.000384  0.000698
text            0.000384  0.000698
messaging       0.000384  0.000698
tricky          0.000384  0.000698
painful         0.000384  0.000698
lasted          0.000384  0.000698
blew            0.000384  0.000698
flop            0.000384  0.000698
smudged         0.000384  0.000698
disappoint      0.000384  0.000698
infra           0.000384  0.000698
irda            0.000384  0.000698
answer          0.000384  0.000698

[1214 rows x 2 columns]

## FASE TESTING

In [ ]:
f = open('amazontesting.txt', encoding="utf8")
test = f.readlines()

dTest = Preprocessing(test)

global dfTest
dfTest = pd.DataFrame(dTest).transpose()

dfTest

0             1       2        3       4      5          6    \
0        plug          tied  jiggle    dozen  needle  waste  seperated   
1      unless       charger    plug  hundred  wasted  money       mere   
2   converter  conversation    line  contact   money   time    started   
3        None       lasting  decent  imagine    None   None     notice   
4        None  minutesmajor  volume      fun    None   None  excessive   
5        None          None    None  sending    None   None     static   
6        None          None    None     None    None   None    garbled   
7        None          None    None     None    None   None      sound   
8        None          None    None     None    None   None    headset   
9        None          None    None     None    None   None       None   
10       None          None    None     None    None   None       None   
11       None          None    None     None    None   None       None   
12       None          None    None     None    None   None       None   

            7       8          9    ...      240       241        242     243  \
0        design  advise      click  ...     love  earpiece  excellent   using   
1           odd  fooled       make  ...  feature      None       hand    home   
2          clip    None     wonder  ...     form      None       free  stereo   
3   comfortable    None  mechanism  ...   factor      None       tool    None   
4          None    None       None  ...     None      None       None    None   
5          None    None       None  ...     None      None       None    None   
6          None    None       None  ...     None      None       None    None   
7          None    None       None  ...     None      None       None    None   
8          None    None       None  ...     None      None       None    None   
9          None    None       None  ...     None      None       None    None   
10         None    None       None  ...     None      None       None    None   
11         None    None       None  ...     None      None       None    None   
12         None    None       None  ...     None      None       None    None   

           244         245   246      247   248      249  
0      product       month  None  battery  it's     love  
1   incredible        it's  None     life  item  headset  
2        value  flawlessly  None     None  None     None  
3         None        None  None     None  None     None  
4         None        None  None     None  None     None  
5         None        None  None     None  None     None  
6         None        None  None     None  None     None  
7         None        None  None     None  None     None  
8         None        None  None     None  None     None  
9         None        None  None     None  None     None  
10        None        None  None     None  None     None  
11        None        None  None     None  None     None  
12        None        None  None     None  None     None  

[13 rows x 250 columns]

In [ ]:
term_uji = []
for i in dfTest.columns:
    temp = []
    for j in dfTest[i]:
        if j in list(LLHood.index) and j is not None:
            temp.append(j)
            
    term_uji.append(temp)
    
dfTerm = pd.DataFrame(term_uji).transpose()
dfTerm

0             1       2        3       4      5        6            7    \
0  plug       charger    plug    dozen  wasted  waste  started       design   
1  None  conversation    line  contact   money  money   static         clip   
2  None       lasting  decent  sending    None   time    sound  comfortable   
3  None          None  volume     None    None   None  headset         None   
4  None          None    None     None    None   None     None         None   
5  None          None    None     None    None   None     None         None   
6  None          None    None     None    None   None     None         None   
7  None          None    None     None    None   None     None         None   
8  None          None    None     None    None   None     None         None   
9  None          None    None     None    None   None     None         None   

      8     9    ...      240       241        242    243      244  \
0  advise  make  ...     love  earpiece  excellent  using  product   
1    None  None  ...  feature      None       hand   home    value   
2    None  None  ...     form      None       free   None     None   
3    None  None  ...     None      None       tool   None     None   
4    None  None  ...     None      None       None   None     None   
5    None  None  ...     None      None       None   None     None   
6    None  None  ...     None      None       None   None     None   
7    None  None  ...     None      None       None   None     None   
8    None  None  ...     None      None       None   None     None   
9    None  None  ...     None      None       None   None     None   

          245   246      247   248      249  
0       month  None  battery  it's     love  
1        it's  None     life  item  headset  
2  flawlessly  None     None  None     None  
3        None  None     None  None     None  
4        None  None     None  None     None  
5        None  None     None  None     None  
6        None  None     None  None     None  
7        None  None     None  None     None  
8        None  None     None  None     None  
9        None  None     None  None     None  

[10 rows x 250 columns]

In [ ]:
prior = {'Positif':PriorPositif,'Negatif':PriorNegatif}
prior

{'Positif': 0.49466666666666664, 'Negatif': 0.5386666666666666}

In [ ]:
hasil = []
for i in term_uji:
    temp = {}
    for j in prior:
        temp[j] = np.prod(LLHood.loc[i,j])*prior[j]
    hasil.append(max(temp,key=temp.get))
    
hasil

['Negatif',
 'Negatif',
 'Negatif',
 'Positif',
 'Negatif',
 'Negatif',
 'Positif',
 'Positif',
 'Negatif',
 'Positif',
 'Positif',
 'Negatif',
 'Positif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Positif',
 'Positif',
 'Negatif',
 'Positif',
 'Negatif',
 'Negatif',
 'Positif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Positif',
 'Positif',
 'Positif',
 'Positif',
 'Negatif',
 'Negatif',
 'Positif',
 'Positif',
 'Negatif',
 'Positif',
 'Positif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Positif',
 'Positif',
 'Negatif',
 'Positif',
 'Negatif',
 'Negatif',
 'Positif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Positif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Positif',
 'Positif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Negatif',
 'Ne

In [ ]:
from sklearn.metrics import precision_recall_fscore_support, accuracy_score, confusion_matrix, classification_report

dok_asli = []
for i in test:
    if '0' in i:
        dok_asli.append("Negatif")
    else:
        dok_asli.append("Positif")
    
y_true = dok_asli
y_pred = hasil

precision_recall_fscore_support(y_true, y_pred, average=None, labels=['Negatif','Positif'])

(array([0.67226891, 0.71755725]),
 array([0.68376068, 0.70676692]),
 array([0.6779661 , 0.71212121]),
 array([117, 133], dtype=int64))

In [ ]:
confusion_matrix(y_true,y_pred)

array([[80, 37],
       [39, 94]], dtype=int64)

In [ ]:
accuracy_score(y_true, y_pred)

0.696

In [ ]:
print(classification_report(y_true,y_pred))

              precision    recall  f1-score   support

     Negatif       0.67      0.68      0.68       117
     Positif       0.72      0.71      0.71       133

    accuracy                           0.70       250
   macro avg       0.69      0.70      0.70       250
weighted avg       0.70      0.70      0.70       250



In [ ]:
print(accuracy_score(y_true, y_pred))

0.696
